:toc:
:toc-placement!:

Here is my preamble paragraph, but I could really place the TOC anywhere! Lorem ipsum foo bar baz.

toc::[]
= Title 1
== Subtitle
Here we should be able to use `normal` asciidoc features

= Title 2
== Subtitle

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :exclamation:
:caution-caption: :hand:
:warning-caption: :warning:
endif::[]

[NOTE]
====
A sample note admonition.
We can use gemoji icons in the Asciidoctor markup.
We assign an icon name to the document
attributes `tip-caption`, `note-caption` and `important-caption`.
====

TIP: It works!

IMPORTANT: Asciidoctor is awesome, don't forget!

CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.

WARNING: You have no reason not to use Asciidoctor.

[source]
----
\ifdef::env-github[] <1> (1)
:imagesdir: https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
endif::[]
\ifndef::env-github[] <2>
:imagesdir: ./
endif::[]
----
<1> Use the `ifdef` to customize for online rendering (2)
<2> Use the `ifndef` to customize for offline

Links:
// Links for GitHub
ifdef::env-github,backend-html5[]
  <<book_mgr_getting_started.adoc#getting-started, SUSE Manager Getting Started>>
  <<book_mgr_best_practices.adoc#best-practices, SUSE Manager Best Practices>>
  <<book_suma_reference_manual.adoc#reference-manual, SUSE Manager Reference Manual>>
  <<book_suma_advanced_topics.adoc#advanced-topics, SUSE Manager Advanced Topics>>
endif::[]
// includes for AsciiDoc processing
ifndef::env-github,backend-html5[]
  include::book_mgr_getting_started.adoc[]
  include::book_mgr_best_practices.adoc[]
  include::book_suma_reference_manual.adoc[]
  include::book_suma_advanced_topics.adoc[]
endif::[]
